# Generated by Django 5.0.6 on 2024-07-01 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_alter_post_date_alter_post_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='text',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
